# Generated by Django 4.2.7 on 2023-11-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredientes', models.CharField(max_length=255)),
                ('modo_de_preparo', models.CharField(max_length=1000)),
                ('foto_url', models.URLField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.post'),
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
    ]
