# Generated by Django 4.2.7 on 2023-11-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_rename_review_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie',
            new_name='post',
        ),
    ]
