# Generated by Django 4.2.7 on 2023-12-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_alter_ticket_owner_alter_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='on_sale',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
